import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Logo } from '@/components/logo';
import { HeroSection } from '@/components/landing/hero-section';
import { LogoCarousel } from '@/components/landing/logo-carousel';

export default function Home() {
  return (
      <div className="flex min-h-screen flex-col">
            <header className="container mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="flex h-20 items-center justify-between">
                              <Link href="/" className="flex items-center gap-2">
                                          <Logo className="h-8 w-8 text-primary" />
                                                      <span className="text-xl font-bold tracking-tight text-foreground">
                                                                    CAUSAE 
                                                                                </span>
                                                                                          </Link>
                                                                                                    <nav className="hidden items-center gap-6 text-sm font-medium md:flex">
                                                                                                                <Link
                                                                                                                              href="#features"
                                                                                                                                            className="transition-colors hover:text-primary"
                                                                                                                                                        >
                                                                                                                                                                      Features
                                                                                                                                                                                  </Link>
                                                                                                                                                                                              <Link
                                                                                                                                                                                                            href="#pricing"
                                                                                                                                                                                                                          className="transition-colors hover:text-primary"
                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                    Pricing
                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                            <Link
                                                                                                                                                                                                                                                                                          href="#contact"
                                                                                                                                                                                                                                                                                                        className="transition-colors hover:text-primary"
                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                  Contact
                                                                                                                                                                                                                                                                                                                                              </Link>
                                                                                                                                                                                                                                                                                                                                                        </nav>
                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center gap-4">
                                                                                                                                                                                                                                                                                                                                                                              <Button variant="ghost" asChild>
                                                                                                                                                                                                                                                                                                                                                                                            <Link href="/login">Log In</Link>
                                                                                                                                                                                                                                                                                                                                                                                                        </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                    <Button asChild>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <Link href="/register">Sign Up</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </header>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <main className="flex-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <HeroSection />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <LogoCarousel />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <footer className="bg-muted/50">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="container mx-auto flex flex-col items-center justify-between gap-4 px-4 py-8 sm:px-6 lg:px-8 md:flex-row">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Logo className="h-6 w-6 text-foreground" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-md font-semibold">CAUSAE</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-sm text-muted-foreground">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  © {new Date().getFullYear()} CAUSAE Legaltech. All rights reserved.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex items-center gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                href="#"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="text-sm text-muted-foreground transition-colors hover:text-foreground"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Terms of Service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              href="#"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="text-sm text-muted-foreground transition-colors hover:text-foreground"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Privacy Policy
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

    